vim.g.mapleader=" "
vim.keymap.set("n","<leader>cd",vim.cmd.Ex)
vim.keymap.set("n", "<leader>k", "<CMD>Oil<CR>", { desc = "Open Oil file explorer" })
vim.keymap.set("n","<leader>q",vim.cmd.q)
vim.keymap.set("n","<leader>nt",vim.cmd.vsplit)
vim.keymap.set("n","<leader>w",vim.cmd.bd)
vim.keymap.set("n","<leader>s",vim.cmd.w)
vim.keymap.set("n","<leader>tt",vim.cmd.tabnew)
vim.keymap.set("n", "<leader>tt", ":tabnew<CR>")
vim.keymap.set("n", "<leader>tc", ":tabclose<CR>")
vim.keymap.set("n", "<leader>to", ":tabonly<CR>")
vim.keymap.set("n", "<leader>tn", ":tabnext<CR>")
vim.keymap.set("n", "<leader>tp", ":tabprev<CR>")
vim.keymap.set("n", "<leader>th", ":tabfirst<CR>")
vim.keymap.set("n", "<leader>tl", ":tablast<CR>")
vim.keymap.set("n", "<leader>1", "1gt")
vim.keymap.set("n", "<leader>2", "2gt")
vim.keymap.set("n", "<leader>3", "3gt")
vim.keymap.set("n", "<leader>4", "4gt")
vim.keymap.set("n", "<leader>5", "5gt")
vim.keymap.set("n", "<leader>6", "6gt")
vim.keymap.set("n", "<leader>7", "7gt")
vim.keymap.set("n", "<leader>8", "8gt")
vim.keymap.set("n", "<leader>9", "9gt")
vim.keymap.set("n", "<leader><Tab>", "<C-^>")
